version: "3"
services:
  webapp:
    image: sirily11/secyan_webapp
    ports:
      - "8080:80"
    container_name: "codegen-webapp"

  server:
    image: sirily11/secyan_gen
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    container_name: "codegen-server"
    command: python3 index.py
    environment:
      host: db
      password: password
      user: user
      database: test

  test:
    image: sirily11/secyan_gen_test
    build:
      context: ./
      dockerfile: docker/test.dockerfile
    volumes:
      - ./:/app
    depends_on:
      - db
    command: pipenv run pytest
    environment:
      host: db
      password: password
      user: user
      database: tpch
      in_docker: 1

  db:
    build:
      context: ./
      dockerfile: docker/postgres.dockerfile

    restart: always
    image: sirily11/secyan_db
    ports:
    - 5431:5432
    volumes:
    - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user