version: "3.9"
services:
  webapp:
    build:
      context: ./
      dockerfile: docker/webapp.dockerfile

    ports:
      - "8080:80"
    container_name: "codegen-webapp"

  server:
    build:
      context: ./
      dockerfile: docker/server.dockerfile
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    container_name: "codegen-server"
    command: pipenv run python index.py
    environment:
      host: db
      password: password
      user: user
      database: test
  test:
    build:
      context: ./
      dockerfile: docker/server.dockerfile
    volumes:
      - ./:/app
    command: pipenv run pytest
    depends_on:
      - db
    environment:
      host: db
      password: password
      user: user
      database: test
      in_docker: 1

  db:
    build:
      context: ./
      dockerfile: docker/postgres.dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user