name: Build and test

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: dschep/install-pipenv-action@v1
      - name: Pipenv install
        run: |
          pipenv install
      - name: Test with pytest
        run: |
          pipenv run python -m pytest