name: Build and test

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build images
        run: docker-compose build test

      - name: Up db
        run: docker-compose up -d db

      - name: Run tests
        run: docker-compose run test
